<?php

namespace Database\Seeders;

use App\Models\Province;
use App\Models\Regency;
use Illuminate\Database\Seeder;

class ProvinceSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            'Aceh' => [
                ['name' => 'Simeulue', 'type' => 'kabupaten'],
                ['name' => 'Aceh Singkil', 'type' => 'kabupaten'],
                ['name' => 'Aceh Selatan', 'type' => 'kabupaten'],
                ['name' => 'Aceh Tenggara', 'type' => 'kabupaten'],
                ['name' => 'Aceh Timur', 'type' => 'kabupaten'],
                ['name' => 'Aceh Tengah', 'type' => 'kabupaten'],
                ['name' => 'Aceh Barat', 'type' => 'kabupaten'],
                ['name' => 'Aceh Besar', 'type' => 'kabupaten'],
                ['name' => 'Pidie', 'type' => 'kabupaten'],
                ['name' => 'Bireuen', 'type' => 'kabupaten'],
                ['name' => 'Aceh Utara', 'type' => 'kabupaten'],
                ['name' => 'Aceh Barat Daya', 'type' => 'kabupaten'],
                ['name' => 'Gayo Lues', 'type' => 'kabupaten'],
                ['name' => 'Aceh Tamiang', 'type' => 'kabupaten'],
                ['name' => 'Nagan Raya', 'type' => 'kabupaten'],
                ['name' => 'Aceh Jaya', 'type' => 'kabupaten'],
                ['name' => 'Bener Meriah', 'type' => 'kabupaten'],
                ['name' => 'Pidie Jaya', 'type' => 'kabupaten'],
                ['name' => 'Banda Aceh', 'type' => 'kota'],
                ['name' => 'Sabang', 'type' => 'kota'],
                ['name' => 'Langsa', 'type' => 'kota'],
                ['name' => 'Lhokseumawe', 'type' => 'kota'],
                ['name' => 'Subulussalam', 'type' => 'kota'],
            ],
            'Sumatera Utara' => [
                ['name' => 'Nias', 'type' => 'kabupaten'],
                ['name' => 'Mandailing Natal', 'type' => 'kabupaten'],
                ['name' => 'Tapanuli Selatan', 'type' => 'kabupaten'],
                ['name' => 'Tapanuli Tengah', 'type' => 'kabupaten'],
                ['name' => 'Tapanuli Utara', 'type' => 'kabupaten'],
                ['name' => 'Toba', 'type' => 'kabupaten'],
                ['name' => 'Labuhanbatu', 'type' => 'kabupaten'],
                ['name' => 'Asahan', 'type' => 'kabupaten'],
                ['name' => 'Simalungun', 'type' => 'kabupaten'],
                ['name' => 'Dairi', 'type' => 'kabupaten'],
                ['name' => 'Karo', 'type' => 'kabupaten'],
                ['name' => 'Deli Serdang', 'type' => 'kabupaten'],
                ['name' => 'Langkat', 'type' => 'kabupaten'],
                ['name' => 'Nias Selatan', 'type' => 'kabupaten'],
                ['name' => 'Humbang Hasundutan', 'type' => 'kabupaten'],
                ['name' => 'Pakpak Bharat', 'type' => 'kabupaten'],
                ['name' => 'Samosir', 'type' => 'kabupaten'],
                ['name' => 'Serdang Bedagai', 'type' => 'kabupaten'],
                ['name' => 'Batu Bara', 'type' => 'kabupaten'],
                ['name' => 'Padang Lawas Utara', 'type' => 'kabupaten'],
                ['name' => 'Padang Lawas', 'type' => 'kabupaten'],
                ['name' => 'Labuhanbatu Selatan', 'type' => 'kabupaten'],
                ['name' => 'Labuhanbatu Utara', 'type' => 'kabupaten'],
                ['name' => 'Nias Utara', 'type' => 'kabupaten'],
                ['name' => 'Nias Barat', 'type' => 'kabupaten'],
                ['name' => 'Sibolga', 'type' => 'kota'],
                ['name' => 'Tanjungbalai', 'type' => 'kota'],
                ['name' => 'Pematangsiantar', 'type' => 'kota'],
                ['name' => 'Tebing Tinggi', 'type' => 'kota'],
                ['name' => 'Medan', 'type' => 'kota'],
                ['name' => 'Binjai', 'type' => 'kota'],
                ['name' => 'Padangsidimpuan', 'type' => 'kota'],
                ['name' => 'Gunungsitoli', 'type' => 'kota'],
            ],
            'Sumatera Barat' => [
                ['name' => 'Kepulauan Mentawai', 'type' => 'kabupaten'],
                ['name' => 'Pesisir Selatan', 'type' => 'kabupaten'],
                ['name' => 'Solok', 'type' => 'kabupaten'],
                ['name' => 'Sijunjung', 'type' => 'kabupaten'],
                ['name' => 'Tanah Datar', 'type' => 'kabupaten'],
                ['name' => 'Padang Pariaman', 'type' => 'kabupaten'],
                ['name' => 'Agam', 'type' => 'kabupaten'],
                ['name' => 'Lima Puluh Kota', 'type' => 'kabupaten'],
                ['name' => 'Pasaman', 'type' => 'kabupaten'],
                ['name' => 'Solok Selatan', 'type' => 'kabupaten'],
                ['name' => 'Dharmasraya', 'type' => 'kabupaten'],
                ['name' => 'Pasaman Barat', 'type' => 'kabupaten'],
                ['name' => 'Padang', 'type' => 'kota'],
                ['name' => 'Solok', 'type' => 'kota'],
                ['name' => 'Sawahlunto', 'type' => 'kota'],
                ['name' => 'Padang Panjang', 'type' => 'kota'],
                ['name' => 'Bukittinggi', 'type' => 'kota'],
                ['name' => 'Payakumbuh', 'type' => 'kota'],
                ['name' => 'Pariaman', 'type' => 'kota'],
            ],
            'Riau' => [
                ['name' => 'Kuantan Singingi', 'type' => 'kabupaten'],
                ['name' => 'Indragiri Hulu', 'type' => 'kabupaten'],
                ['name' => 'Indragiri Hilir', 'type' => 'kabupaten'],
                ['name' => 'Pelalawan', 'type' => 'kabupaten'],
                ['name' => 'Siak', 'type' => 'kabupaten'],
                ['name' => 'Kampar', 'type' => 'kabupaten'],
                ['name' => 'Rokan Hulu', 'type' => 'kabupaten'],
                ['name' => 'Bengkalis', 'type' => 'kabupaten'],
                ['name' => 'Rokan Hilir', 'type' => 'kabupaten'],
                ['name' => 'Kepulauan Meranti', 'type' => 'kabupaten'],
                ['name' => 'Pekanbaru', 'type' => 'kota'],
                ['name' => 'Dumai', 'type' => 'kota'],
            ],
            'Jambi' => [
                ['name' => 'Kerinci', 'type' => 'kabupaten'],
                ['name' => 'Merangin', 'type' => 'kabupaten'],
                ['name' => 'Sarolangun', 'type' => 'kabupaten'],
                ['name' => 'Batang Hari', 'type' => 'kabupaten'],
                ['name' => 'Muaro Jambi', 'type' => 'kabupaten'],
                ['name' => 'Tanjung Jabung Timur', 'type' => 'kabupaten'],
                ['name' => 'Tanjung Jabung Barat', 'type' => 'kabupaten'],
                ['name' => 'Tebo', 'type' => 'kabupaten'],
                ['name' => 'Bungo', 'type' => 'kabupaten'],
                ['name' => 'Jambi', 'type' => 'kota'],
                ['name' => 'Sungai Penuh', 'type' => 'kota'],
            ],
            'Sumatera Selatan' => [
                ['name' => 'Ogan Komering Ulu', 'type' => 'kabupaten'],
                ['name' => 'Ogan Komering Ilir', 'type' => 'kabupaten'],
                ['name' => 'Muara Enim', 'type' => 'kabupaten'],
                ['name' => 'Lahat', 'type' => 'kabupaten'],
                ['name' => 'Musi Rawas', 'type' => 'kabupaten'],
                ['name' => 'Musi Banyuasin', 'type' => 'kabupaten'],
                ['name' => 'Banyuasin', 'type' => 'kabupaten'],
                ['name' => 'Ogan Komering Ulu Selatan', 'type' => 'kabupaten'],
                ['name' => 'Ogan Komering Ulu Timur', 'type' => 'kabupaten'],
                ['name' => 'Ogan Ilir', 'type' => 'kabupaten'],
                ['name' => 'Empat Lawang', 'type' => 'kabupaten'],
                ['name' => 'Penukal Abab Lematang Ilir', 'type' => 'kabupaten'],
                ['name' => 'Musi Rawas Utara', 'type' => 'kabupaten'],
                ['name' => 'Palembang', 'type' => 'kota'],
                ['name' => 'Prabumulih', 'type' => 'kota'],
                ['name' => 'Pagar Alam', 'type' => 'kota'],
                ['name' => 'Lubuklinggau', 'type' => 'kota'],
            ],
            'Bengkulu' => [
                ['name' => 'Bengkulu Selatan', 'type' => 'kabupaten'],
                ['name' => 'Rejang Lebong', 'type' => 'kabupaten'],
                ['name' => 'Bengkulu Utara', 'type' => 'kabupaten'],
                ['name' => 'Kaur', 'type' => 'kabupaten'],
                ['name' => 'Seluma', 'type' => 'kabupaten'],
                ['name' => 'Mukomuko', 'type' => 'kabupaten'],
                ['name' => 'Lebong', 'type' => 'kabupaten'],
                ['name' => 'Kepahiang', 'type' => 'kabupaten'],
                ['name' => 'Bengkulu Tengah', 'type' => 'kabupaten'],
                ['name' => 'Bengkulu', 'type' => 'kota'],
            ],
            'Lampung' => [
                ['name' => 'Lampung Barat', 'type' => 'kabupaten'],
                ['name' => 'Tanggamus', 'type' => 'kabupaten'],
                ['name' => 'Lampung Selatan', 'type' => 'kabupaten'],
                ['name' => 'Lampung Timur', 'type' => 'kabupaten'],
                ['name' => 'Lampung Tengah', 'type' => 'kabupaten'],
                ['name' => 'Lampung Utara', 'type' => 'kabupaten'],
                ['name' => 'Way Kanan', 'type' => 'kabupaten'],
                ['name' => 'Tulangbawang', 'type' => 'kabupaten'],
                ['name' => 'Pesawaran', 'type' => 'kabupaten'],
                ['name' => 'Pringsewu', 'type' => 'kabupaten'],
                ['name' => 'Mesuji', 'type' => 'kabupaten'],
                ['name' => 'Tulangbawang Barat', 'type' => 'kabupaten'],
                ['name' => 'Pesisir Barat', 'type' => 'kabupaten'],
                ['name' => 'Bandar Lampung', 'type' => 'kota'],
                ['name' => 'Metro', 'type' => 'kota'],
            ],
            'Kepulauan Bangka Belitung' => [
                ['name' => 'Bangka', 'type' => 'kabupaten'],
                ['name' => 'Belitung', 'type' => 'kabupaten'],
                ['name' => 'Bangka Barat', 'type' => 'kabupaten'],
                ['name' => 'Bangka Tengah', 'type' => 'kabupaten'],
                ['name' => 'Bangka Selatan', 'type' => 'kabupaten'],
                ['name' => 'Belitung Timur', 'type' => 'kabupaten'],
                ['name' => 'Pangkalpinang', 'type' => 'kota'],
            ],
            'Kepulauan Riau' => [
                ['name' => 'Karimun', 'type' => 'kabupaten'],
                ['name' => 'Bintan', 'type' => 'kabupaten'],
                ['name' => 'Natuna', 'type' => 'kabupaten'],
                ['name' => 'Lingga', 'type' => 'kabupaten'],
                ['name' => 'Kepulauan Anambas', 'type' => 'kabupaten'],
                ['name' => 'Batam', 'type' => 'kota'],
                ['name' => 'Tanjungpinang', 'type' => 'kota'],
            ],
            'DKI Jakarta' => [
                ['name' => 'Kepulauan Seribu', 'type' => 'kabupaten'],
                ['name' => 'Jakarta Selatan', 'type' => 'kota'],
                ['name' => 'Jakarta Timur', 'type' => 'kota'],
                ['name' => 'Jakarta Pusat', 'type' => 'kota'],
                ['name' => 'Jakarta Barat', 'type' => 'kota'],
                ['name' => 'Jakarta Utara', 'type' => 'kota'],
            ],
            'Jawa Barat' => [
                ['name' => 'Bogor', 'type' => 'kabupaten'],
                ['name' => 'Sukabumi', 'type' => 'kabupaten'],
                ['name' => 'Cianjur', 'type' => 'kabupaten'],
                ['name' => 'Bandung', 'type' => 'kabupaten'],
                ['name' => 'Garut', 'type' => 'kabupaten'],
                ['name' => 'Tasikmalaya', 'type' => 'kabupaten'],
                ['name' => 'Ciamis', 'type' => 'kabupaten'],
                ['name' => 'Kuningan', 'type' => 'kabupaten'],
                ['name' => 'Cirebon', 'type' => 'kabupaten'],
                ['name' => 'Majalengka', 'type' => 'kabupaten'],
                ['name' => 'Sumedang', 'type' => 'kabupaten'],
                ['name' => 'Indramayu', 'type' => 'kabupaten'],
                ['name' => 'Subang', 'type' => 'kabupaten'],
                ['name' => 'Purwakarta', 'type' => 'kabupaten'],
                ['name' => 'Karawang', 'type' => 'kabupaten'],
                ['name' => 'Bekasi', 'type' => 'kabupaten'],
                ['name' => 'Bandung Barat', 'type' => 'kabupaten'],
                ['name' => 'Pangandaran', 'type' => 'kabupaten'],
                ['name' => 'Bogor', 'type' => 'kota'],
                ['name' => 'Sukabumi', 'type' => 'kota'],
                ['name' => 'Bandung', 'type' => 'kota'],
                ['name' => 'Cirebon', 'type' => 'kota'],
                ['name' => 'Bekasi', 'type' => 'kota'],
                ['name' => 'Depok', 'type' => 'kota'],
                ['name' => 'Cimahi', 'type' => 'kota'],
                ['name' => 'Tasikmalaya', 'type' => 'kota'],
                ['name' => 'Banjar', 'type' => 'kota'],
            ],
            'Jawa Tengah' => [
                ['name' => 'Cilacap', 'type' => 'kabupaten'],
                ['name' => 'Banyumas', 'type' => 'kabupaten'],
                ['name' => 'Purbalingga', 'type' => 'kabupaten'],
                ['name' => 'Banjarnegara', 'type' => 'kabupaten'],
                ['name' => 'Kebumen', 'type' => 'kabupaten'],
                ['name' => 'Purworejo', 'type' => 'kabupaten'],
                ['name' => 'Wonosobo', 'type' => 'kabupaten'],
                ['name' => 'Magelang', 'type' => 'kabupaten'],
                ['name' => 'Boyolali', 'type' => 'kabupaten'],
                ['name' => 'Klaten', 'type' => 'kabupaten'],
                ['name' => 'Sukoharjo', 'type' => 'kabupaten'],
                ['name' => 'Wonogiri', 'type' => 'kabupaten'],
                ['name' => 'Karanganyar', 'type' => 'kabupaten'],
                ['name' => 'Sragen', 'type' => 'kabupaten'],
                ['name' => 'Grobogan', 'type' => 'kabupaten'],
                ['name' => 'Blora', 'type' => 'kabupaten'],
                ['name' => 'Rembang', 'type' => 'kabupaten'],
                ['name' => 'Pati', 'type' => 'kabupaten'],
                ['name' => 'Kudus', 'type' => 'kabupaten'],
                ['name' => 'Jepara', 'type' => 'kabupaten'],
                ['name' => 'Demak', 'type' => 'kabupaten'],
                ['name' => 'Semarang', 'type' => 'kabupaten'],
                ['name' => 'Temanggung', 'type' => 'kabupaten'],
                ['name' => 'Kendal', 'type' => 'kabupaten'],
                ['name' => 'Batang', 'type' => 'kabupaten'],
                ['name' => 'Pekalongan', 'type' => 'kabupaten'],
                ['name' => 'Pemalang', 'type' => 'kabupaten'],
                ['name' => 'Tegal', 'type' => 'kabupaten'],
                ['name' => 'Brebes', 'type' => 'kabupaten'],
                ['name' => 'Magelang', 'type' => 'kota'],
                ['name' => 'Surakarta', 'type' => 'kota'],
                ['name' => 'Salatiga', 'type' => 'kota'],
                ['name' => 'Semarang', 'type' => 'kota'],
                ['name' => 'Pekalongan', 'type' => 'kota'],
                ['name' => 'Tegal', 'type' => 'kota'],
            ],
            'DI Yogyakarta' => [
                ['name' => 'Kulon Progo', 'type' => 'kabupaten'],
                ['name' => 'Bantul', 'type' => 'kabupaten'],
                ['name' => 'Gunungkidul', 'type' => 'kabupaten'],
                ['name' => 'Sleman', 'type' => 'kabupaten'],
                ['name' => 'Yogyakarta', 'type' => 'kota'],
            ],
            'Jawa Timur' => [
                ['name' => 'Pacitan', 'type' => 'kabupaten'],
                ['name' => 'Ponorogo', 'type' => 'kabupaten'],
                ['name' => 'Trenggalek', 'type' => 'kabupaten'],
                ['name' => 'Tulungagung', 'type' => 'kabupaten'],
                ['name' => 'Blitar', 'type' => 'kabupaten'],
                ['name' => 'Kediri', 'type' => 'kabupaten'],
                ['name' => 'Malang', 'type' => 'kabupaten'],
                ['name' => 'Lumajang', 'type' => 'kabupaten'],
                ['name' => 'Jember', 'type' => 'kabupaten'],
                ['name' => 'Banyuwangi', 'type' => 'kabupaten'],
                ['name' => 'Bondowoso', 'type' => 'kabupaten'],
                ['name' => 'Situbondo', 'type' => 'kabupaten'],
                ['name' => 'Probolinggo', 'type' => 'kabupaten'],
                ['name' => 'Pasuruan', 'type' => 'kabupaten'],
                ['name' => 'Sidoarjo', 'type' => 'kabupaten'],
                ['name' => 'Mojokerto', 'type' => 'kabupaten'],
                ['name' => 'Jombang', 'type' => 'kabupaten'],
                ['name' => 'Nganjuk', 'type' => 'kabupaten'],
                ['name' => 'Madiun', 'type' => 'kabupaten'],
                ['name' => 'Magetan', 'type' => 'kabupaten'],
                ['name' => 'Ngawi', 'type' => 'kabupaten'],
                ['name' => 'Bojonegoro', 'type' => 'kabupaten'],
                ['name' => 'Tuban', 'type' => 'kabupaten'],
                ['name' => 'Lamongan', 'type' => 'kabupaten'],
                ['name' => 'Gresik', 'type' => 'kabupaten'],
                ['name' => 'Bangkalan', 'type' => 'kabupaten'],
                ['name' => 'Sampang', 'type' => 'kabupaten'],
                ['name' => 'Pamekasan', 'type' => 'kabupaten'],
                ['name' => 'Sumenep', 'type' => 'kabupaten'],
                ['name' => 'Kediri', 'type' => 'kota'],
                ['name' => 'Blitar', 'type' => 'kota'],
                ['name' => 'Malang', 'type' => 'kota'],
                ['name' => 'Probolinggo', 'type' => 'kota'],
                ['name' => 'Pasuruan', 'type' => 'kota'],
                ['name' => 'Mojokerto', 'type' => 'kota'],
                ['name' => 'Madiun', 'type' => 'kota'],
                ['name' => 'Surabaya', 'type' => 'kota'],
                ['name' => 'Batu', 'type' => 'kota'],
            ],
            'Banten' => [
                ['name' => 'Pandeglang', 'type' => 'kabupaten'],
                ['name' => 'Lebak', 'type' => 'kabupaten'],
                ['name' => 'Tangerang', 'type' => 'kabupaten'],
                ['name' => 'Serang', 'type' => 'kabupaten'],
                ['name' => 'Tangerang', 'type' => 'kota'],
                ['name' => 'Cilegon', 'type' => 'kota'],
                ['name' => 'Serang', 'type' => 'kota'],
                ['name' => 'Tangerang Selatan', 'type' => 'kota'],
            ],
            'Bali' => [
                ['name' => 'Jembrana', 'type' => 'kabupaten'],
                ['name' => 'Tabanan', 'type' => 'kabupaten'],
                ['name' => 'Badung', 'type' => 'kabupaten'],
                ['name' => 'Gianyar', 'type' => 'kabupaten'],
                ['name' => 'Klungkung', 'type' => 'kabupaten'],
                ['name' => 'Bangli', 'type' => 'kabupaten'],
                ['name' => 'Karangasem', 'type' => 'kabupaten'],
                ['name' => 'Buleleng', 'type' => 'kabupaten'],
                ['name' => 'Denpasar', 'type' => 'kota'],
            ],
            'Nusa Tenggara Barat' => [
                ['name' => 'Lombok Barat', 'type' => 'kabupaten'],
                ['name' => 'Lombok Tengah', 'type' => 'kabupaten'],
                ['name' => 'Lombok Timur', 'type' => 'kabupaten'],
                ['name' => 'Sumbawa', 'type' => 'kabupaten'],
                ['name' => 'Dompu', 'type' => 'kabupaten'],
                ['name' => 'Bima', 'type' => 'kabupaten'],
                ['name' => 'Sumbawa Barat', 'type' => 'kabupaten'],
                ['name' => 'Lombok Utara', 'type' => 'kabupaten'],
                ['name' => 'Mataram', 'type' => 'kota'],
                ['name' => 'Bima', 'type' => 'kota'],
            ],
            'Nusa Tenggara Timur' => [
                ['name' => 'Sumba Barat', 'type' => 'kabupaten'],
                ['name' => 'Sumba Timur', 'type' => 'kabupaten'],
                ['name' => 'Kupang', 'type' => 'kabupaten'],
                ['name' => 'Timor Tengah Selatan', 'type' => 'kabupaten'],
                ['name' => 'Timor Tengah Utara', 'type' => 'kabupaten'],
                ['name' => 'Belu', 'type' => 'kabupaten'],
                ['name' => 'Alor', 'type' => 'kabupaten'],
                ['name' => 'Lembata', 'type' => 'kabupaten'],
                ['name' => 'Flores Timur', 'type' => 'kabupaten'],
                ['name' => 'Sikka', 'type' => 'kabupaten'],
                ['name' => 'Ende', 'type' => 'kabupaten'],
                ['name' => 'Ngada', 'type' => 'kabupaten'],
                ['name' => 'Manggarai', 'type' => 'kabupaten'],
                ['name' => 'Rote Ndao', 'type' => 'kabupaten'],
                ['name' => 'Manggarai Barat', 'type' => 'kabupaten'],
                ['name' => 'Sumba Tengah', 'type' => 'kabupaten'],
                ['name' => 'Sumba Barat Daya', 'type' => 'kabupaten'],
                ['name' => 'Nagekeo', 'type' => 'kabupaten'],
                ['name' => 'Manggarai Timur', 'type' => 'kabupaten'],
                ['name' => 'Sabu Raijua', 'type' => 'kabupaten'],
                ['name' => 'Malaka', 'type' => 'kabupaten'],
                ['name' => 'Kupang', 'type' => 'kota'],
            ],
            'Kalimantan Barat' => [
                ['name' => 'Sambas', 'type' => 'kabupaten'],
                ['name' => 'Bengkayang', 'type' => 'kabupaten'],
                ['name' => 'Landak', 'type' => 'kabupaten'],
                ['name' => 'Mempawah', 'type' => 'kabupaten'],
                ['name' => 'Sanggau', 'type' => 'kabupaten'],
                ['name' => 'Ketapang', 'type' => 'kabupaten'],
                ['name' => 'Sintang', 'type' => 'kabupaten'],
                ['name' => 'Kapuas Hulu', 'type' => 'kabupaten'],
                ['name' => 'Sekadau', 'type' => 'kabupaten'],
                ['name' => 'Melawi', 'type' => 'kabupaten'],
                ['name' => 'Kayong Utara', 'type' => 'kabupaten'],
                ['name' => 'Kubu Raya', 'type' => 'kabupaten'],
                ['name' => 'Pontianak', 'type' => 'kota'],
                ['name' => 'Singkawang', 'type' => 'kota'],
            ],
            'Kalimantan Tengah' => [
                ['name' => 'Kotawaringin Barat', 'type' => 'kabupaten'],
                ['name' => 'Kotawaringin Timur', 'type' => 'kabupaten'],
                ['name' => 'Kapuas', 'type' => 'kabupaten'],
                ['name' => 'Barito Selatan', 'type' => 'kabupaten'],
                ['name' => 'Barito Utara', 'type' => 'kabupaten'],
                ['name' => 'Barito Timur', 'type' => 'kabupaten'],
                ['name' => 'Sukamara', 'type' => 'kabupaten'],
                ['name' => 'Lamandau', 'type' => 'kabupaten'],
                ['name' => 'Seruyan', 'type' => 'kabupaten'],
                ['name' => 'Katingan', 'type' => 'kabupaten'],
                ['name' => 'Pulang Pisau', 'type' => 'kabupaten'],
                ['name' => 'Gunung Mas', 'type' => 'kabupaten'],
                ['name' => 'Murung Raya', 'type' => 'kabupaten'],
                ['name' => 'Palangka Raya', 'type' => 'kota'],
            ],
            'Kalimantan Selatan' => [
                ['name' => 'Tanah Laut', 'type' => 'kabupaten'],
                ['name' => 'Kota Baru', 'type' => 'kabupaten'],
                ['name' => 'Banjar', 'type' => 'kabupaten'],
                ['name' => 'Barito Kuala', 'type' => 'kabupaten'],
                ['name' => 'Tapin', 'type' => 'kabupaten'],
                ['name' => 'Hulu Sungai Selatan', 'type' => 'kabupaten'],
                ['name' => 'Hulu Sungai Tengah', 'type' => 'kabupaten'],
                ['name' => 'Hulu Sungai Utara', 'type' => 'kabupaten'],
                ['name' => 'Tabalong', 'type' => 'kabupaten'],
                ['name' => 'Tanah Bumbu', 'type' => 'kabupaten'],
                ['name' => 'Balangan', 'type' => 'kabupaten'],
                ['name' => 'Banjarmasin', 'type' => 'kota'],
                ['name' => 'Banjarbaru', 'type' => 'kota'],
            ],
            'Kalimantan Timur' => [
                ['name' => 'Paser', 'type' => 'kabupaten'],
                ['name' => 'Kutai Barat', 'type' => 'kabupaten'],
                ['name' => 'Kutai Kartanegara', 'type' => 'kabupaten'],
                ['name' => 'Kutai Timur', 'type' => 'kabupaten'],
                ['name' => 'Berau', 'type' => 'kabupaten'],
                ['name' => 'Mahakam Ulu', 'type' => 'kabupaten'],
                ['name' => 'Penajam Paser Utara', 'type' => 'kabupaten'],
                ['name' => 'Balikpapan', 'type' => 'kota'],
                ['name' => 'Samarinda', 'type' => 'kota'],
                ['name' => 'Bontang', 'type' => 'kota'],
            ],
            'Kalimantan Utara' => [
                ['name' => 'Malinau', 'type' => 'kabupaten'],
                ['name' => 'Bulungan', 'type' => 'kabupaten'],
                ['name' => 'Tana Tidung', 'type' => 'kabupaten'],
                ['name' => 'Nunukan', 'type' => 'kabupaten'],
                ['name' => 'Tarakan', 'type' => 'kota'],
            ],
            'Sulawesi Utara' => [
                ['name' => 'Bolaang Mongondow', 'type' => 'kabupaten'],
                ['name' => 'Minahasa', 'type' => 'kabupaten'],
                ['name' => 'Kepulauan Sangihe', 'type' => 'kabupaten'],
                ['name' => 'Kepulauan Talaud', 'type' => 'kabupaten'],
                ['name' => 'Minahasa Selatan', 'type' => 'kabupaten'],
                ['name' => 'Minahasa Utara', 'type' => 'kabupaten'],
                ['name' => 'Bolaang Mongondow Utara', 'type' => 'kabupaten'],
                ['name' => 'Siau Tagulandang Biaro', 'type' => 'kabupaten'],
                ['name' => 'Minahasa Tenggara', 'type' => 'kabupaten'],
                ['name' => 'Bolaang Mongondow Timur', 'type' => 'kabupaten'],
                ['name' => 'Bolaang Mongondow Selatan', 'type' => 'kabupaten'],
                ['name' => 'Manado', 'type' => 'kota'],
                ['name' => 'Bitung', 'type' => 'kota'],
                ['name' => 'Tomohon', 'type' => 'kota'],
                ['name' => 'Kotamobagu', 'type' => 'kota'],
            ],
            'Sulawesi Tengah' => [
                ['name' => 'Banggai Kepulauan', 'type' => 'kabupaten'],
                ['name' => 'Banggai', 'type' => 'kabupaten'],
                ['name' => 'Morowali', 'type' => 'kabupaten'],
                ['name' => 'Poso', 'type' => 'kabupaten'],
                ['name' => 'Donggala', 'type' => 'kabupaten'],
                ['name' => 'Toli-Toli', 'type' => 'kabupaten'],
                ['name' => 'Buol', 'type' => 'kabupaten'],
                ['name' => 'Parigi Moutong', 'type' => 'kabupaten'],
                ['name' => 'Tojo Una-Una', 'type' => 'kabupaten'],
                ['name' => 'Sigi', 'type' => 'kabupaten'],
                ['name' => 'Banggai Laut', 'type' => 'kabupaten'],
                ['name' => 'Morowali Utara', 'type' => 'kabupaten'],
                ['name' => 'Palu', 'type' => 'kota'],
            ],
            'Sulawesi Selatan' => [
                ['name' => 'Kepulauan Selayar', 'type' => 'kabupaten'],
                ['name' => 'Bulukumba', 'type' => 'kabupaten'],
                ['name' => 'Bantaeng', 'type' => 'kabupaten'],
                ['name' => 'Jeneponto', 'type' => 'kabupaten'],
                ['name' => 'Takalar', 'type' => 'kabupaten'],
                ['name' => 'Gowa', 'type' => 'kabupaten'],
                ['name' => 'Sinjai', 'type' => 'kabupaten'],
                ['name' => 'Maros', 'type' => 'kabupaten'],
                ['name' => 'Pangkajene Kepulauan', 'type' => 'kabupaten'],
                ['name' => 'Barru', 'type' => 'kabupaten'],
                ['name' => 'Bone', 'type' => 'kabupaten'],
                ['name' => 'Soppeng', 'type' => 'kabupaten'],
                ['name' => 'Wajo', 'type' => 'kabupaten'],
                ['name' => 'Sidenreng Rappang', 'type' => 'kabupaten'],
                ['name' => 'Pinrang', 'type' => 'kabupaten'],
                ['name' => 'Enrekang', 'type' => 'kabupaten'],
                ['name' => 'Luwu', 'type' => 'kabupaten'],
                ['name' => 'Tana Toraja', 'type' => 'kabupaten'],
                ['name' => 'Luwu Utara', 'type' => 'kabupaten'],
                ['name' => 'Luwu Timur', 'type' => 'kabupaten'],
                ['name' => 'Toraja Utara', 'type' => 'kabupaten'],
                ['name' => 'Makassar', 'type' => 'kota'],
                ['name' => 'Parepare', 'type' => 'kota'],
                ['name' => 'Palopo', 'type' => 'kota'],
            ],
            'Sulawesi Tenggara' => [
                ['name' => 'Kolaka', 'type' => 'kabupaten'],
                ['name' => 'Konawe', 'type' => 'kabupaten'],
                ['name' => 'Muna', 'type' => 'kabupaten'],
                ['name' => 'Buton', 'type' => 'kabupaten'],
                ['name' => 'Konawe Selatan', 'type' => 'kabupaten'],
                ['name' => 'Bombana', 'type' => 'kabupaten'],
                ['name' => 'Wakatobi', 'type' => 'kabupaten'],
                ['name' => 'Kolaka Utara', 'type' => 'kabupaten'],
                ['name' => 'Buton Utara', 'type' => 'kabupaten'],
                ['name' => 'Konawe Utara', 'type' => 'kabupaten'],
                ['name' => 'Kolaka Timur', 'type' => 'kabupaten'],
                ['name' => 'Konawe Kepulauan', 'type' => 'kabupaten'],
                ['name' => 'Muna Barat', 'type' => 'kabupaten'],
                ['name' => 'Buton Tengah', 'type' => 'kabupaten'],
                ['name' => 'Buton Selatan', 'type' => 'kabupaten'],
                ['name' => 'Kendari', 'type' => 'kota'],
                ['name' => 'Baubau', 'type' => 'kota'],
            ],
            'Gorontalo' => [
                ['name' => 'Boalemo', 'type' => 'kabupaten'],
                ['name' => 'Gorontalo', 'type' => 'kabupaten'],
                ['name' => 'Pohuwato', 'type' => 'kabupaten'],
                ['name' => 'Bone Bolango', 'type' => 'kabupaten'],
                ['name' => 'Gorontalo Utara', 'type' => 'kabupaten'],
                ['name' => 'Gorontalo', 'type' => 'kota'],
            ],
            'Sulawesi Barat' => [
                ['name' => 'Majene', 'type' => 'kabupaten'],
                ['name' => 'Polewali Mandar', 'type' => 'kabupaten'],
                ['name' => 'Mamasa', 'type' => 'kabupaten'],
                ['name' => 'Mamuju', 'type' => 'kabupaten'],
                ['name' => 'Mamuju Tengah', 'type' => 'kabupaten'],
                ['name' => 'Pasangkayu', 'type' => 'kabupaten'],
            ],
            'Maluku' => [
                ['name' => 'Maluku Tenggara Barat', 'type' => 'kabupaten'],
                ['name' => 'Maluku Tenggara', 'type' => 'kabupaten'],
                ['name' => 'Maluku Tengah', 'type' => 'kabupaten'],
                ['name' => 'Buru', 'type' => 'kabupaten'],
                ['name' => 'Kepulauan Aru', 'type' => 'kabupaten'],
                ['name' => 'Seram Bagian Barat', 'type' => 'kabupaten'],
                ['name' => 'Seram Bagian Timur', 'type' => 'kabupaten'],
                ['name' => 'Maluku Barat Daya', 'type' => 'kabupaten'],
                ['name' => 'Buru Selatan', 'type' => 'kabupaten'],
                ['name' => 'Ambon', 'type' => 'kota'],
                ['name' => 'Tual', 'type' => 'kota'],
            ],
            'Maluku Utara' => [
                ['name' => 'Halmahera Barat', 'type' => 'kabupaten'],
                ['name' => 'Halmahera Tengah', 'type' => 'kabupaten'],
                ['name' => 'Kepulauan Sula', 'type' => 'kabupaten'],
                ['name' => 'Halmahera Selatan', 'type' => 'kabupaten'],
                ['name' => 'Halmahera Utara', 'type' => 'kabupaten'],
                ['name' => 'Halmahera Timur', 'type' => 'kabupaten'],
                ['name' => 'Pulau Morotai', 'type' => 'kabupaten'],
                ['name' => 'Pulau Taliabu', 'type' => 'kabupaten'],
                ['name' => 'Ternate', 'type' => 'kota'],
                ['name' => 'Tidore Kepulauan', 'type' => 'kota'],
            ],
            'Papua Barat' => [
                ['name' => 'Manokwari', 'type' => 'kabupaten'],
                ['name' => 'Fakfak', 'type' => 'kabupaten'],
                ['name' => 'Kaimana', 'type' => 'kabupaten'],
                ['name' => 'Teluk Wondama', 'type' => 'kabupaten'],
                ['name' => 'Teluk Bintuni', 'type' => 'kabupaten'],
                ['name' => 'Manokwari Selatan', 'type' => 'kabupaten'],
                ['name' => 'Pegunungan Arfak', 'type' => 'kabupaten'],
                ['name' => 'Sorong', 'type' => 'kota'],
            ],
            'Papua Barat Daya' => [
                ['name' => 'Sorong', 'type' => 'kabupaten'],
                ['name' => 'Raja Ampat', 'type' => 'kabupaten'],
                ['name' => 'Tambrauw', 'type' => 'kabupaten'],
                ['name' => 'Maybrat', 'type' => 'kabupaten'],
            ],
            'Papua' => [
                ['name' => 'Jayapura', 'type' => 'kabupaten'],
                ['name' => 'Sarmi', 'type' => 'kabupaten'],
                ['name' => 'Keerom', 'type' => 'kabupaten'],
                ['name' => 'Kepulauan Yapen', 'type' => 'kabupaten'],
                ['name' => 'Biak Numfor', 'type' => 'kabupaten'],
                ['name' => 'Supiori', 'type' => 'kabupaten'],
                ['name' => 'Mamberamo Raya', 'type' => 'kabupaten'],
                ['name' => 'Waropen', 'type' => 'kabupaten'],
                ['name' => 'Jayapura', 'type' => 'kota'],
            ],
            'Papua Selatan' => [
                ['name' => 'Merauke', 'type' => 'kabupaten'],
                ['name' => 'Boven Digoel', 'type' => 'kabupaten'],
                ['name' => 'Mappi', 'type' => 'kabupaten'],
                ['name' => 'Asmat', 'type' => 'kabupaten'],
            ],
            'Papua Tengah' => [
                ['name' => 'Nabire', 'type' => 'kabupaten'],
                ['name' => 'Paniai', 'type' => 'kabupaten'],
                ['name' => 'Mimika', 'type' => 'kabupaten'],
                ['name' => 'Puncak Jaya', 'type' => 'kabupaten'],
                ['name' => 'Deiyai', 'type' => 'kabupaten'],
                ['name' => 'Dogiyai', 'type' => 'kabupaten'],
                ['name' => 'Intan Jaya', 'type' => 'kabupaten'],
                ['name' => 'Puncak', 'type' => 'kabupaten'],
            ],
            'Papua Pegunungan' => [
                ['name' => 'Jayawijaya', 'type' => 'kabupaten'],
                ['name' => 'Pegunungan Bintang', 'type' => 'kabupaten'],
                ['name' => 'Yahukimo', 'type' => 'kabupaten'],
                ['name' => 'Tolikara', 'type' => 'kabupaten'],
                ['name' => 'Mamberamo Tengah', 'type' => 'kabupaten'],
                ['name' => 'Yalimo', 'type' => 'kabupaten'],
                ['name' => 'Lanny Jaya', 'type' => 'kabupaten'],
                ['name' => 'Nduga', 'type' => 'kabupaten'],
            ],
        ];

        foreach ($data as $provinceName => $regencies) {
            $province = Province::firstOrCreate(['name' => $provinceName]);
            foreach ($regencies as $r) {
                Regency::firstOrCreate(
                    ['province_id' => $province->id, 'name' => $r['name'], 'type' => $r['type']]
                );
            }
        }
    }
}
